### PR TITLE
Test Diactoros Factory with PHP 5.4

### PR DESCRIPTION
**Pull request by dunglas**
They now support PHP 5.4 too.

### CODE REVIEW

**Comment by xabbuh** [comment]
:+1: Test failures on PHP 5.6 are unrelated. But we should take a look at the cause.

**Comment by dunglas** [comment]
For the test failure see symfony/symfony#15249

**Comment by xabbuh** [comment]
ping  @symfony/deciders

**Comment by fabpot** [comment]
:+1:

**Comment by jakzal** [comment]
:+1:

**Comment by fabpot** [comment]
Thank you @dunglas.

**Pull request merged**
