### PR TITLE
Fix for wrong type passed to moveTo()

### PR DESCRIPTION
**Pull request by lemon-juice**
Issue #102

### CODE REVIEW

**Comment by derrabus** [comment]
Can you write a test to make sure this functionality won't break again?

**Comment by lemon-juice** [comment]
I'm sorry but I don't have much experience with writing tests. I might have a go at it but I would need some time to research the topic and experiment. If you need it now then it would be better to delegate it to someone else.

**Review by derrabus — APPROVED** [review]
No worries. Thank you very much for analysing and fixing the bug.

**Review by dunglas — APPROVED** [review]

**Comment by derrabus** [comment]
Thank you @lemon-juice.

**Comment by lemon-juice** [comment]
OK, I'm glad to see it integrated quickly!

**Pull request merged**
